version: '3.8'

services:
  telegram-scraper:
    build: .
    container_name: telegram-scraper
    ports:
      - "8003:8000"
    environment:
      # Telegram API credentials
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - TELEGRAM_PHONE=${TELEGRAM_PHONE}
      - TELEGRAM_SESSION_NAME=${TELEGRAM_SESSION_NAME:-telegram_scraper}
      
      # Database
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./telegram_news.db}
      
      # GCS Configuration
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
      - GCS_CREDENTIALS_PATH=${GCS_CREDENTIALS_PATH}
      
      # API Configuration
      - API_HOST=0.0.0.0
      - API_PORT=8000
      
      # Scraping Configuration
      - RATE_LIMIT_DELAY=${RATE_LIMIT_DELAY:-2}
      
      # Storage Configuration
      - IMAGES_DIR=./images
      - MAX_IMAGE_SIZE=${MAX_IMAGE_SIZE:-5242880}
      
      # Logging Configuration
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      
    volumes:
      # Persist database
      - ./data:/app/data
      # Persist logs
      - ./logs:/app/logs
      # Persist images
      - ./images:/app/images
      # Persist Telegram session
      - ./telegram_session:/app/telegram_session
      # GCS credentials
      - ./credentials:/app/credentials:ro
      
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: telegram-scraper-network 